[tool.black]
line-length = 80

[tool.mypy]
strict = true
warn_unused_configs = true
show_error_codes = true
show_column_numbers = true
warn_no_return = false
no_implicit_optional = false
ignore_missing_imports = true
exclude = ".git/, __pycache__/, ./venv/"
