# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.structureMenu = QtWidgets.QMenu(self.menubar)
        self.structureMenu.setObjectName("structureMenu")
        self.tableMenu = QtWidgets.QMenu(self.menubar)
        self.tableMenu.setObjectName("tableMenu")
        MainWindow.setMenuBar(self.menubar)
        self.openDB = QtWidgets.QAction(MainWindow)
        self.openDB.setObjectName("openDB")
        self.createDB = QtWidgets.QAction(MainWindow)
        self.createDB.setObjectName("createDB")
        self.commitDB = QtWidgets.QAction(MainWindow)
        self.commitDB.setObjectName("commitDB")
        self.createTable = QtWidgets.QAction(MainWindow)
        self.createTable.setObjectName("createTable")
        self.createColumn = QtWidgets.QAction(MainWindow)
        self.createColumn.setObjectName("createColumn")
        self.fileMenu.addAction(self.openDB)
        self.fileMenu.addAction(self.createDB)
        self.fileMenu.addAction(self.commitDB)
        self.structureMenu.addAction(self.createTable)
        self.structureMenu.addAction(self.createColumn)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.structureMenu.menuAction())
        self.menubar.addAction(self.tableMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "Редактор базы данных")
        )
        self.fileMenu.setTitle(_translate("MainWindow", "Файл"))
        self.structureMenu.setTitle(_translate("MainWindow", "Структура"))
        self.tableMenu.setTitle(_translate("MainWindow", "Таблица"))
        self.openDB.setText(_translate("MainWindow", "Открыть"))
        self.createDB.setText(_translate("MainWindow", "Создать"))
        self.commitDB.setText(_translate("MainWindow", "Сохранить"))
        self.createTable.setText(_translate("MainWindow", "Создать таблицу"))
        self.createColumn.setText(_translate("MainWindow", "Создать колонку"))
