on:
  push:
    branches:
      - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r dev_requirements.txt
      - name: Run tests
        run: pytest --cov=./ --cov-report=xml
      - name: Generate report
        run: coverage xml
      - name: Upload coverate to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
